version: '3'

services:
  db:
    image: keinos/sqlite3:latest
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
  