# Generated by Django 2.2.10 on 2020-04-23 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200423_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.CreateModel(
            name='ItemImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='images', verbose_name='item_files')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this_item', to='core.Item')),
            ],
        ),
    ]
