# Generated by Django 2.2.10 on 2020-07-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
